### PR TITLE
Api proposal

### PR DESCRIPTION
**Pull request by lopezm94**
## Interface

Here is the API proposal, it contains the name changes stated on issue #75 and also the GMRES doc fix requested on issue #60. The current test and benchmarks are updated for the new syntax.

### Input

Positional arguments not necessary for a method call are now keyword arguments. All methods have two new keyword arguments and two return options:

*Keywords*:

- verbose
- plot

*Return options*:

1. Standard result of the function
2. Standard result of the function, `ConvergenceHistory` (This was the only option before)

For the first one you only need to call as it is currently implemented in the package.
For the second one the method call should always look like this:
```julia
method(Master, ...) #Master is a custom type made only for dispatching
```

### Output

The new `ConvergenceHistory` internals are much different than before:
```julia
type ConvergenceHistory{T}
    mvps::Int    # Matvec products
    mtvps::Int     # Transposed matvec products
    iters::Int     # Total number of iterations
    restart::T    # Restart size
    isconverged::Bool    # Convergence flag
    tol::Dict{Symbol, Real}    # Tolerances
    data::Dict{Symbol, VecOrMat}    # Convergence data (Not necessarily residuals)
end
typealias PlainHistory ConvergenceHistory{Void}
typealias RestartedHistory ConvergenceHistory{Int}
```

Most are self explanatory. The `data` attribute can only have info meant to be stored and updated at each iteration (that's why it only accepts vectors or matrices). For methods like svdl storing information such as the ritz or beta values is now possible inside the `data` attribute.

#### Plots 

For quick and dirty plotting, just set `plot` keyword and info about the method will be plotted using UnicodePlots.

For more advanced  request, `ConvergenceHistory` has custom recipe so it is compatible with [Plots.jl](https://github.com/tbreloff/Plots.jl).

### Docs

As soon as this is merged I'll proceed to complete the docs, for a quick look of the current theme check [here](http://juanlopezm.me/IterativeSolvers.jl/library/public/).

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Instead of a `showplot`, you should do a plot recipe (to make a `plot(::ConvergenceHistory)` ) to Plots.jl so that it's more customizable and so that you don't have to have a plotting package as a dependency (just RecipesBase).

**Comment by lopezm94** [comment]
Could there be a single recipe for multiple plots? `data::Dict{Symbol, VecOrMat}` will have multiple plot options.

**Comment by ChrisRackauckas** [comment]
Yes, I think you could do a series recipe to handle that. @tbreloff would know.

**Comment by tbreloff** [comment]
Sure that would be straightforward I think. Look at doing a "user recipe"

**Comment by lopezm94** [comment]
Plots.jl is amazing, thanks for the package. If I understand correctly the way to print everything would be to design a vertical `@layout` and do a `@series` for each plot. However, I think I'll make a new plot(::ConvergenceHistory) definition and then a `@userplot` to plot each data element.

**Comment by lopezm94** [comment]
Ok, I added support for Plots.jl via recipes. Do you treat the data in any special way before plotting @tbreloff? whenever I try to to manually plot an error pop ups, but if I use Plots.jl then everything works fine. I ask because we will most likely keep UnicodePlots for easy and quick plotting.

**Comment by tbreloff** [comment]
I peeked at the recipe and it seems like that should work. What error are
you seeing?

**Comment by lopezm94** [comment]
The recipe works perfectly, my question is a bit unrelated to recipes.

Inside the package we do our own plots besides recipes, so since Plots.jl is too big we use `UnicodePlots`, however sometimes this error pops up:

```julia
ERROR: InexactError()
 in Plot at /home/juan/.julia/v0.4/UnicodePlots/src/plot.jl:150
```

But when using your package everything works fine. I was wondering if you process the numbers in any special way before sending them to `UnicodePlots`, so I can emulate it here.

**Comment by tbreloff** [comment]
I see. Can you convert your other plotting to recipes as well?

**Comment by ChrisRackauckas** [comment]
>  so since Plots.jl is too big we use UnicodePlots

You don't need to have Plots.jl as a dependency for defining recipes, just `RecipesBase` (which is rather small).

**Comment by lopezm94** [comment]
I think I'm not expressing myself correctly. I know `RecipesBase` is lightweight, but if I want to plot something without having the user import `Plots.jl` (if he wants to plot the recipe thats up to him), then this package needs another dependency since `RecipesBase` can't plot on it s own. That's why currently this PR plots with `UnicodePlots`. For example:

```julia
svdl(Master, rand(10,10), plot=true)  #Supposed to plot on its own
```

So in this call `IterativeSolvers.jl` needs to plot, recipes can't be plotted without Plots.jl and that's why I use `UnicodePlots` instead. What I was trying to say is that when I call `UnicodePlots` on my own (no recipes, no Plots.jl ) I get this inexact errors sometimes, that's all in I'm saying. Was just hoping tbreloff would know because his package needs to deal with `UnicodePlots` API and issues. I imagine it must be because of some NaN number that I'm passing.

**Comment by ChrisRackauckas** [comment]
I see what you mean.

**Comment by lopezm94** [comment]
It is a `UnicodePlots` bug (see Evizero/UnicodePlots.jl/issues/51). I'll try to make a PR

**Comment by lopezm94** [comment]
The [docs](http://juanlopezm.me/IterativeSolvers.jl/) are out if anyone is interested.

**Comment by lopezm94** [comment]
This PR became too big, I'll separate this in smaller PRs. Sorry for the troubles and the relentless coveralls messages.

**Pull request closed without merging**
